### ISSUE TITLE
renaming map output modules

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#141]
`SurfaceMap` writes a png to disk
`SameTimePlaceMap` returns a raster in the workflow object
`PrintMap` plots a simple, non-interactive map

These should have more intuitive names and more explicit docs.

Renaming them will necessitate changing tests etc. too

**Comment by AugustT** [comment]
*"Renaming them will necessitate changing tests etc. too"* not any more :)

**Comment by AugustT** [comment]
I suggest that all of these should print the device, offer the option to save, and return the raster to the workflow object.

And.... aren't 'PrintMap' and 'SameTimePlaceMap' basically the same??

**Comment by timcdlucas** [comment]
It could all be one module with args

    PrintMap(displayNow = TRUE, save = NULL)

Those are probably bad argument names. But you need to be able turning off printing to the main R plot thing, because if you run 20 models, you don't want them to all plot. 
Could have `save = NULL` doesn't save a png and if you give save a directory, it saves the pngs there. 
 I agree it should always return the raster to the workflow object.

PrintMap and SameTimePlaceMap are the same except where stuff goes. PrintMap ONLY goes to the default plotting device. 
Which was a terrible idea.
SameTimePlaceMap ONLY goes in the workflow object.

**Comment by AugustT** [comment]
Sorry, all three of these are basically the same.

I suggest we retain only `PrintMap`

**Comment by AugustT** [comment]
snap

**Comment by AugustT** [comment]
There is currently an issue with the saving as if you have a list of models the second plot overwrites the first. This is part of a wider problem which is that you cannot easily tell where things have come from downstream of a list

**Comment by AugustT** [comment]
I have fixed the over writing issue by adding in name indexing. In this way if the file name already exits it is appended with a number.

It would be better to be able to name them (eg, GAM.png, logisticRegression.png, ...)

**Comment by AugustT** [comment]
Oh god these modules appear ALL OVER my testing.... yawn, find-replace, find-replace

**Comment by AugustT** [comment]
PrintMap has been updated to do everything. The other 2 modules were removed from the repo but this caused our package on CRAN to fail tests (I got an email from Kurt). I have put these 2 modules back up to stop this however consider them deprecated.
