### ISSUE TITLE
add example workflow for figshare

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#219]
with unique tag & some sort of metadata

**Comment by AugustT** [comment]
Here it is:

http://figshare.com/articles/Tom_August_Workflow_number_1/1601910

I have created a function 'ZoonFigshare' for uploading workflows (an adaptation of the module). The author adding of rfigshare is a bit buggy but otherwise it all seems to be working. I have set the tag 'zoonWorkflow' as a default
