### ISSUE TITLE
ModuleHelp function does not open the cached help URL 

### ISSUE THREAD

**Issue by RTbecard** [zoonproject/zoon#228]
The `DisplayModuleHelp` function in the file `R/HelpFunctions.r` does not load the cached help file into either the viewer or any system browser.  Tested on Ubuntu 14.04 (a crouton installation on a chromebook).  This does not throw any error message, and just results in no visible result from calling the function.

The issue comes from **line 97** where the function `browseURL(htmlFile)` does not have the `browser` argument passed to it.  I resolved the issue by adding the browse argument which was already defined in **line 83** to it resulting in: `browseURL(htmlFile,browser)`.  This resolved the issue and resulted in the help file being displayed in the RStudio viewer.

**Comment by goldingn** [comment]
Thanks for this, looks like a good catch!

Unfortunately both Tom and I will be away from working laptops until February, so we've both downed tools on zoon until then.

One of us will check this out and hopefully merge as soon as we are back though. Please let us know of any other bugs/fixes you in the mean time, and sorry for the inactivity!

Oh, and Merry Christmas!

**Comment by AugustT** [comment]
**I'm back**

@RTbecard It sounds like you have spotted a peach of a bug. The best way to solve this and for you to get credit is for you to put in a pull request. Looks like you might be new to Github, so to do this you need to fork this repository so that you have a copy in your personal space, then make changes to your copy and then click the pull request button.

Otherwise if this all sounds like a lot of hassle just let me know and I can make the change myself.

Tom

**Comment by AugustT** [comment]
@RTbecard Since I have not heard back, and I'm working on the code today I will make this change for you.

Thanks again,

Tom

**Comment by RTbecard** [comment]
Hey Tom,

Ya, no worries, I got held up with some other work this week so I didn't
get the time yet.  Thanks for taking care of it for me!

James
