### ISSUE TITLE
add on-the-fly coordinate system transformation

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#285]
Currently zoon only handles data in the WGS84 (latlong) coordinate reference system (CRS), but many others are available and are used for different datasets that people might like to use in zoon (I think @cvisintin ran into this recently with some rasters he has in a nice projection for Australia). Where everything is provided by the user in the same non-latlong CRS, zoon should work. However it will break if the user (or another user) tries to plug in data with a different CRS.

It shouldn't be too hard to convert points and rasters on the fly so that they all line up, using the functions `rgdal::spTransform()` and `raster::projectRaster()` (though the latter can be quite slow).

We could take the strategy that if more than one CRS is detected in all the rasters and occurrences, everything gets converted to latlong. For rasters this should be easy to check (all `Raster*` objects have a `projection` slot and accessor function), but for occurrences this will require a column* giving the CRS for each datapoint, recorded as a proj4 string.

We could either 1) add a CRS column to the expected columns of df, or 2) make CRS an optional column and assume latlong if the CRS column is missing or for NAs.

Option 1 might be clearer to users, but would require more work modifying docs and tests.
Option 2 should be relatively quick to set up.

I would suggest we pursue option 2 first, and do the rest of the work to switch to option 1 if it looks like it would be preferable.

------

*I think this is preferable having metadata for the occurrence dataframe, since `Chain`ing occurrence modules will `rbind` them without having to worry about this. We can then loop through batches of rows in the different CRSs to convert them prior to the extract step.

**Comment by RTbecard** [comment]
Might be a good idea to change the `lat` `long` column names in `.df` to something more generalized like `x` & `y`sooner rather than later...  I'm just thinking in regards to reducing the work load later on in regards to having to update modules which rely on pulling coords from the names of `.df` frame columns.

**Comment by AugustT** [comment]
I have a working solution for occurrence data. If a crs column is given the data are transformed, if a crs column is not given the data are assumed to be lat/long. I currently have a logical test to see if the data are lat/long and and error is thrown if they aren't (i.e. values of lat over 90). This means you cannot enter, say eastings and northings, without specifying a crs column,

My issue now is with rasters, which like Nick, I thought would be easy to deal with, but they aren't. Reprojecting rasters is complicated as a raster is a grid (nice and square) and a reprojection of a raster is not nice and square and therefore this sort of thing happens

```r
LoadModule('NaiveRandomRaster')
ras <- NaiveRandomRaster(extent = c(0,100000,0,100000), res = 10000)
latlong <- "+init=epsg:4326"
eastnorth <- '+init=epsg:27700'
projection(ras) <- eastnorth
plot(ras)
```
![image](https://cloud.githubusercontent.com/assets/3987564/19075384/9ae75114-8a3c-11e6-98f4-d11508cdebc0.png)
```r
rasLL <- projectRaster(ras, crs = CRS(latlong))
plot(rasLL)
```
![image](https://cloud.githubusercontent.com/assets/3987564/19075405/adb694b2-8a3c-11e6-9915-c744aa76851a.png)
I think what we all expected (or just me!?) was something like this to happen
```r
# Convert the original to a polygon
ras_poly <- rasterToPolygons(ras)
spplot(ras_poly)
```
![image](https://cloud.githubusercontent.com/assets/3987564/19075430/c6e0aefa-8a3c-11e6-8a49-b1cea9123d60.png)
```r
# Convert the polygon CRS and replot
ras_poly_LL <- spTransform(ras_poly, CRSobj = CRS(latlong))
spplot(ras_poly_LL)
```
![image](https://cloud.githubusercontent.com/assets/3987564/19075458/e444e286-8a3c-11e6-96a1-c235c13cd037.png)

So my question is this. If we want to be able to do reprojections of rasters on the fly do we have to move to a process where rasters are converted to polygons for reprojection? This is going to add a big overhead in terms of processing. The original conversion using `projectRaster` is not satisfactory either. Have I missed something? Should I be using `projectRaster` in a different way?

I can change my use of `projectRaster` to improve results. By specifying the output resolution and method I can get a better approximation of what we desire but this adds overheads and requires us to make a judgement about the resolution required. 

```r
rasLL_n <- projectRaster(ras, crs = CRS(latlong), res = 0.001, method = 'ngb')
plot(rasLL_n)
```
![image](https://cloud.githubusercontent.com/assets/3987564/19075977/f656552a-8a3e-11e6-8e5b-413a6879298a.png)

Do I even need to reproject the raster? Can we instead reproject the occurrence data to the projection of the raster. This would probably be much more efficient. We could assume that if the raster has no CRS it is in the same CRS as the occurrence data, Thoughts much appreciated @goldingn @timcdlucas

**Comment by timcdlucas** [comment]
I guess I expected there to be weird corners and stuff on reprojection of a raster.

My brain hurts to much to think about this carefully but I feel we should project occurrence points to the projection of the raster. You lose information reprojecting rasters, you don't lose information projecting points. Projecting points is cheaper, projecting rasters is slow. Projecting both to latlong is pointless? 

Agree that if the raster has no CRS, should be assumed to be the same as points (perhaps with a warning that noone will read).

I can't remember where it came up, but stacking rasters of different projections has been mentioned. Then the rasters will have to be reprojected.

**Comment by AugustT** [comment]
Yes, the stacking thing is a related issue. At the moment I convert all occurrence data to lat long so that they can be chained without any issue. Something similar will need to be done for rasters

**Comment by goldingn** [comment]
I think I was expecting the nasty raster version, rather than the polygons. It's not normally that nasty at larger spatial scales. 

Reprojecting points will probably be the right thing in most situations. Only when rasters are from different sources and have different projections should this be necessary. It would also be useful to have access to this functionality for spatially explicit models or validation procedures, which normally expect constant distances (which lat long doesnt have)

**Comment by AugustT** [comment]
Okay, so this is what I have done.

Covariate modules are now run first. If there is a chain then the rasters are converted to the most frequent projection amongst those to be combined and then they are cut down to the minimal area that they have in common before being stacked

```r
LoadModule('NaiveRandomRaster')

# Lat long raster res 1
ras1 <- NaiveRandomRaster(extent = c(-10, 10, 45, 65),
                          res = 1,
                          seed = 123)

# lat long raster stack res 5
ras2a <- NaiveRandomRaster(extent = c(-15, 15, 50, 70),
                           res = 5,
                           seed = 123)
ras2b <- NaiveRandomRaster(extent = c(-15, 15, 50, 70),
                           res = 5,
                           seed = 124)

ras2 <- stack(ras2a, ras2b)

# easting northing (high res)
ras3 <- NaiveRandomRaster(extent = c(200000, 800000, 200000, 800000),
                          res = 20000,
                          seed = 123,
                          projection = '+init=epsg:27700')

plot(ras1)
```
![image](https://cloud.githubusercontent.com/assets/3987564/19481211/1b944020-9545-11e6-8c1f-359d499593e4.png)
```r
plot(ras2)
```
![image](https://cloud.githubusercontent.com/assets/3987564/19481228/267fd922-9545-11e6-9206-519edc2958d2.png)
```r
plot(ras3)
```
![image](https://cloud.githubusercontent.com/assets/3987564/19481244/3087af26-9545-11e6-910e-d0a5631814cd.png)
```r
# CombineRasters tries to intellegently combine across coordinate systems
# extents and resolutions. It takes and returns a list
x <- CombineRasters(list(ras1, ras2, ras3)) 

# This prints an informative message to console
```
`Covariate layers have been converted to a new projection to be combined: +proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0 To save time make sure all your covariates have the same projection.
Not all rasters have the same extent, they will be cropped to the minimal area covered by all rasters: -6.22277770866662, 5.48122229133338, 50.6108870412878, 57.9908870412878`
```r
# Lets see the result
plot(raster::stack(x))
```
![image](https://cloud.githubusercontent.com/assets/3987564/19481320/6e86b31c-9545-11e6-96a8-141bc6af66f1.png)


Next I worked on how this process is combined with occurrence data. Since these are now run *after* covariate modules I have used the CRS of the covariate layers to dictate the CRS used for the occurrence points. 

Occurrence points are assumed to be lat/long unless the user supplies a `CRS` column. The lat/long are transformed to the CRS of the covariates in extract and combine.

Here are a few example workflows

```r
# Use an occurrence dataset of eastings and northings in combination
# with a raster layer using lat/long
w1 <- workflow(occurrence = NaiveRandomPresence(extent = c(0, 1000000, 0, 1000000),
                                                    seed = 123,
                                                    projection = '+init=epsg:27700'),
               covariate  = UKAir,
               process    = Background(n=70),
               model      = LogisticRegression,
               output     = PrintMap)
# message to console
```
`Occurrence data will be transformed from +init=epsg:27700 to +proj=longlat +ellps=WGS84 to match covariate data`
![image](https://cloud.githubusercontent.com/assets/3987564/19481724/d2de4036-9546-11e6-8953-8e2c3d9cadba.png)

```r
# Try 2 rasters in different projections. 
LoadModule('NaiveRandomRaster')
new_ras <- NaiveRandomRaster()
new_ras <- projectRaster(new_ras, crs = CRS('+init=epsg:27700'))

workflow(occurrence = NaiveRandomPresence(extent = c(0, 1000000, 0, 1000000),
                                          seed = 123,
                                          projection = '+init=epsg:27700'),
         covariate  = list(NaiveRandomRaster, LocalRaster(new_ras)),
         process    = Background(n=70),
         model      = LogisticRegression,
         output     = PrintMap)
```
`Occurrence data will be transformed from +init=epsg:27700 to +proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0 to match covariate data
Occurrence data will be transformed from +init=epsg:27700 to +init=epsg:27700 +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +datum=OSGB36 +units=m +no_defs +ellps=airy +towgs84=446.448,-125.157,542.060,0.1502,0.2470,0.8421,-20.4894 to match covariate data`
![image](https://cloud.githubusercontent.com/assets/3987564/19481940/7b841a30-9547-11e6-8fe2-980879e75c34.png)
![image](https://cloud.githubusercontent.com/assets/3987564/19481954/8791bd64-9547-11e6-94cd-3c36581519e0.png)

```r
# A hard example

# 2 occurrence datasets in different projections 
# 3 rasters in different projections and resolutions, chained
w3 <- workflow(occurrence = list(NaiveRandomPresence(extent = c(0, 1000000, 0, 1000000),
                                                     seed = 123,
                                                     projection = '+init=epsg:27700'),
                                 NaiveRandomPresence(extent = c(-5, 5, 50, 60),
                                                     seed = 123)),
               covariate  = Chain(NaiveRandomRaster,
                                  NaiveRandomRaster(extent = c(0, 1000000, 0, 1000000),
                                                    seed = 123,
                                                    res = 10000,
                                                    projection = '+init=epsg:27700'),
                                  UKAir),
               process    = Background(n=70),
               model      = LogisticRegression,
               output     = PrintMap)

# We get a few messages
```
`Covariate rasters have been converted to WGS84 latitude/longitude in order to be combined. To save time make sure all your covariates have the same projection.
Not all rasters have the same extent, they will be cropped to the minimal area covered by all rasters: -9.6819634374082, 9.1060365625918, 48.8297267476504, 59.6955267476504
Occurrence data will be transformed from +init=epsg:27700 to +init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 to match covariate data
Occurrence data does not have a "crs" column, zoon will assume it is in the same projection as the covariate data
Warning messages:
1: In ExtractAndCombData(x, covariate.output[[1]]) :
  3 extracted covariate values are NA. This may cause issues for some models
2: In ExtractAndCombData(x, covariate.output[[1]]) :
  32 occurrence points are outside the raster extent and have been removed before modelling leaving 968 occurrence points
3: In ExtractAndCombData(x, covariate.output[[1]]) :
  63 extracted covariate values are NA. This may cause issues for some models`
![image](https://cloud.githubusercontent.com/assets/3987564/19484693/506ae5b4-9550-11e6-8c31-f1d4552576fe.png)
![image](https://cloud.githubusercontent.com/assets/3987564/19484681/4855ccfe-9550-11e6-805f-6919ff5baedf.png)

Coming in a PR soon

**Comment by goldingn** [comment]
Awesome work!

Tagging @cvisintin here, as I think this functionality was something needed to handle some modules he's been working on. Casey, this is now merged into master, so zoon installed from Github should handle multiple reference systems in rasters and occurrence data on the fly.

**Comment by cvisintin** [comment]
Well done!  I will give it a go.  Sorry I have been so slack with the 
contributions...a very nice project indeed!

Cheers,

Casey Visintin

/PhD Candidate/
Quantitative and Applied Ecology Group <http://qaeco.com>
School of BioSciences
University of Melbourne
Parkville | VIC 3010 | Australia
Mobile: 0434 424 084

P*Please consider the environment before printing this email*

**Comment by AugustT** [comment]
@cvisintin Have you given this a go? It would be good to have feedback if you did. Did it do what you wanted?

**Comment by cvisintin** [comment]
Not yet, but I will.  Thanks for the heads up...

Cheers,

Casey Visintin

/PhD Candidate/
Quantitative and Applied Ecology Group <http://qaeco.com>
School of BioSciences
University of Melbourne
Parkville | VIC 3010 | Australia
Mobile: 0434 424 084

P*Please consider the environment before printing this email*
