### ISSUE TITLE
Travis CI fail on modules

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#381]
Hi all,

I'm getting 
Error in download.file(url = "http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz",  : 

which is preventing my Travis CI checks from passing.  I don't know what this url is. Is it a database used for covariates or something? In which case I'll just restart the travis job later.

Otherwise I'm not sure what's going on. Think my new module looks clean and sensible.

**Comment by goldingn** [comment]
It looks like that download was a non-package dependency of the nloptr package. I'm not sure why it was failing, but probably just some server glitch as it seems to work for me now.

I re-ran one of your travis builds, but now it's erroring because it can't install `rnbn`. That's the same error as @Doi90 has on his PR

@AugustT just had `rnbn` taken off CRAN, presumably because the API is changing over. I think the safest thing would be to delete the NBN module that calls it from the modules repo. @AugustT, any reason to suspect that would break anything?

**Comment by timcdlucas** [comment]
OK, I'll wait to hear on this.

**Comment by AugustT** [comment]
rnbn is now deceased so the corresponding module in zoon should be deleted

**Comment by goldingn** [comment]
Cool, module deleted
