### ISSUE TITLE
GetPackage doesn't autoinstall so travis fails with new packages in new modules

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoon#420]
As pointed out by @AugustT. If you create a module with a so-far-unseen-by-zoon package, the travis build won't know to install it and won't be able to install it without clicking "yes please install". 

Not sure what the fix is. Can we have a global option that disables the "yes please install" bit. So it won't affect normal users? I can't remember the exact TOC for CRAN though.

**Comment by goldingn** [comment]
I think if this is only an issue on Travis, the best fix is to get the missing packages installed on Travis, rather than changing the package.

I think it would be worth adding an option to always install if there's a use case beyond our CI, and if CRAN will accept it. 

I had fixed this issue on Travis for a bunch of modules after the change was made to zoon. I'm on my phone now, and won't have any time today, but you could look back through my commits on modules and see if I did something different for those modules than you tried? Failing that, I should be able to take a look early next week.

**Comment by timcdlucas** [comment]
OK I'll have a look and see if I can work this out.

**Comment by timcdlucas** [comment]
Adding it to depends works. So if we're happy with this plan I'll close this issue for now.

I'll try to get around to adding a few lines to the Build_a_module vignette documenting this until we switch to a newer system.
